//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using DataContractsAndProxy;
using Proxy;

namespace Proxy
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CustomObjectToAuditAuditPoint", Namespace = "http://schemas.datacontract.org/2004/07/Proxy")]
    public partial class CustomObjectToAuditAuditPoint : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid ApplicationIDField;

        private ApplicationName ApplicationNameField;

        private System.DateTime AuditDateTimeStampField;

        private AuditCategory AuditingCategoryField;

        private OriginationID OriginationIDField;

        private string MessageField;

        private System.Collections.Generic.Dictionary<string, string> ParametersField;

        private string ReferenceIDField;

        private Status ReportedStatusField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationID
        {
            get
            {
                return this.ApplicationIDField;
            }
            set
            {
                this.ApplicationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApplicationName ApplicationName
        {
            get
            {
                return this.ApplicationNameField;
            }
            set
            {
                this.ApplicationNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AuditDateTimeStamp
        {
            get
            {
                return this.AuditDateTimeStampField;
            }
            set
            {
                this.AuditDateTimeStampField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuditCategory AuditingCategory
        {
            get
            {
                return this.AuditingCategoryField;
            }
            set
            {
                this.AuditingCategoryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public OriginationID OriginationID
        {
            get
            {
                return this.OriginationIDField;
            }
            set
            {
                this.OriginationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceID
        {
            get
            {
                return this.ReferenceIDField;
            }
            set
            {
                this.ReferenceIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Status ReportedStatus
        {
            get
            {
                return this.ReportedStatusField;
            }
            set
            {
                this.ReportedStatusField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationName", Namespace = "http://schemas.datacontract.org/2004/07/DataContractsAndProxy")]
    public enum ApplicationName : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSpecified = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Service1 = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Service2 = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SomeAutomatedJob = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Service3 = 4,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OriginationID", Namespace = "http://schemas.datacontract.org/2004/07/DataContractsAndProxy")]

    public enum OriginationID : int
    {
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AuditCategory", Namespace = "http://schemas.datacontract.org/2004/07/DataContractsAndProxy")]
    public enum AuditCategory : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SignOn = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SignOut = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueueCount = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueueList = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueueRemove = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueuePlace = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddNotes = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RetrieveFromCentralStore = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountInfoMissingException = 104,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 500,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 501,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Status", Namespace = "http://schemas.datacontract.org/2004/07/DataContractsAndProxy")]
    public enum Status : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Indeterminate = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://DotNetNancy.com/services/AuditService", ConfigurationName = "IAuditService")]
public interface IAuditService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://DotNetNancy.com/services/AuditService/IAuditService/SubmitAudit", ReplyAction = "http://DotNetNancy.com/services/AuditService/IAuditService/SubmitAuditResponse")]
    string SubmitAudit(DataContractsAndProxy.CustomObjectToAuditAuditPoint auditPoint);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IAuditServiceChannel : IAuditService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class AuditServiceClient : System.ServiceModel.ClientBase<IAuditService>, IAuditService
{

    public AuditServiceClient()
    {
    }

    public AuditServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public AuditServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public AuditServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public AuditServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public string SubmitAudit(DataContractsAndProxy.CustomObjectToAuditAuditPoint auditPoint)
    {
        return base.Channel.SubmitAudit(auditPoint);
    }
}
